### PR TITLE
replace evince to qpdfview

### PR DESCRIPTION
**Pull request by kloun**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Or even get rid of it completely? Most browsers can open pdf files just as nice.

**Comment by vkukshiev** [comment]
djvu and ps?

**Comment by AlexDaniel** [comment]
Good point.

**Comment by computermouth** [comment]
qpdfview does require quite a few qt package requirements. With a fresh Beta install I'm showing 48MB of additional requirements. This beats out Okular and Zathura is very... focused. Is there another alternative we could use that's more gtk-friendly?

**Comment by jeisoncg** [comment]
Why change?

**Comment by ko5tas** [comment]
Which one is the fastest to open large files?

**Comment by computermouth** [comment]
apvlv is pretty light, but seems to have only have vim's control scheme (no ui buttons or anything). What about atril? It looks pretty nice on crunch. Has some Mate dependencies, but otherwise seems to fit the bill.

**Comment by vkukshiev** [comment]
atril too good, but I like qpdfview, it support tabs and independent of mate.

**Comment by superfunc** [comment]
What about mupdf? I think its much lower in dependencies and such.

https://packages.debian.org/jessie/mupdf

**Comment by vkukshiev** [comment]
Mupdf only pdf suported.

2015-02-16 21:24 GMT+03:00 Joshua Filstrup notifications@github.com:

**Comment by superfunc** [comment]
What was the matter with evince?

edit: I saw the other issue created. Wanting to get out gtk dependency, ok.

**Comment by computermouth** [comment]
kloun, I'd like to avoid qpdfview because it neither uses the gtk theme nor the icon theme. It'd just look nicer to stick with atril, especially since as a gtk2 fork of evince, it'll probably stay that way.

**Comment by nfultz** [comment]
I've been pretty happy with pdf.js, it's really come a long way in the last several versions.

**Comment by computermouth** [comment]
I'm pretty set on Atril now. Closing issue, if anyone finds a more apt pdfviewer that gets along with gtk and has less outward dependencies than Atril, submit new issue.

**Pull request closed without merging**
